import React from 'react';

// Sample data for the transactions table
const transactionsData = [

  {
    txnId: 'TXN10031',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'Isabella Garcia',
    origin: 'قيد المراجعة',
    status: 'Completed',
    orderId: 'ORD2031',
    txnType: 'Credit',
  },
  {
    txnId: 'TXN10032',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'Noah Wilson',
    origin: 'قيد المراجعة',
    status: 'Pending',
    orderId: 'ORD2032',
    txnType: 'Debit',
  },
  {
    txnId: 'TXN10033',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'Mia Wang',
    origin: 'قيد المراجعة',
    status: 'Refunded',
    orderId: 'ORD2033',
    txnType: 'Credit',
  },
  {
    txnId: 'TXN10034',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'James Anderson',
    origin: 'قيد المراجعة',
    status: 'Completed',
    orderId: 'ORD2034',
    txnType: 'Debit',
  },
  {
    txnId: 'TXN10035',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'Chloe Kim',
    origin: 'قيد المراجعة',
    status: 'Pending',
    orderId: 'ORD2035',
    txnType: 'Credit',
  },
  {
    txnId: 'TXN10036',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'Ethan Lee',
    origin: 'قيد المراجعة',
    status: 'Completed',
    orderId: 'ORD2036',
    txnType: 'Debit',
  },
  {
    txnId: 'TXN10037',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'Olivia Martinez',
    origin: 'قيد المراجعة',
    status: 'Refunded',
    orderId: 'ORD2037',
    txnType: 'Credit',
  },
  {
    txnId: 'TXN10038',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'Jacob Brown',
    origin: 'قيد المراجعة',
    status: 'Pending',
    orderId: 'ORD2038',
    txnType: 'Debit',
  },
  {
    txnId: 'TXN10039',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'Sophia Davis',
    origin: 'قيد المراجعة',
    status: 'Completed',
    orderId: 'ORD2039',
    txnType: 'Credit',
  },
  {
    txnId: 'TXN10040',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'Logan Lopez',
    origin: 'قيد المراجعة',
    status: 'Refunded',
    orderId: 'ORD2040',
    txnType: 'Debit',
  },
  {
    txnId: 'TXN10041',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'William Johnson',
    origin: 'قيد المراجعة',
    status: 'Completed',
    orderId: 'ORD2041',
    txnType: 'Credit',
  },
  {
    txnId: 'TXN10042',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'Ava Smith',
    origin: 'قيد المراجعة',
    status: 'Pending',
    orderId: 'ORD2042',
    txnType: 'Debit',
  },
  {
    txnId: 'TXN10043',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'Harper Lee',
    origin: 'قيد المراجعة',
    status: 'Refunded',
    orderId: 'ORD2043',
    txnType: 'Credit',
  },
  {
    txnId: 'TXN10044',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'Mason Miller',
    origin: 'قيد المراجعة',
    status: 'Completed',
    orderId: 'ORD2044',
    txnType: 'Debit',
  },
  {
    txnId: 'TXN10045',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'Ella Martinez',
    origin: 'قيد المراجعة',
    status: 'Pending',
    orderId: 'ORD2045',
    txnType: 'Credit',
  },
  {
    txnId: 'TXN10046',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'Elijah Hernandez',
    origin: 'قيد المراجعة',
    status: 'Completed',
    orderId: 'ORD2046',
    txnType: 'Debit',
  },
  {
    txnId: 'TXN10047',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'Charlotte Wilson',
    origin: 'قيد المراجعة',
    status: 'Refunded',
    orderId: 'ORD2047',
    txnType: 'Credit',
  },
  {
    txnId: 'TXN10048',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'Amelia Brown',
    origin: 'قيد المراجعة',
    status: 'Pending',
    orderId: 'ORD2048',
    txnType: 'Debit',
  },
  {
    txnId: 'TXN10049',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'Oliver Garcia',
    origin: 'قيد المراجعة',
    status: 'Completed',
    orderId: 'ORD2049',
    txnType: 'Credit',
  },
  {
    txnId: 'TXN10050',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'Sophia Thompson',
    origin: 'قيد المراجعة',
    status: 'Refunded',
    orderId: 'ORD2050',
    txnType: 'Debit',
  },
  {
    txnId: 'TXN10051',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'Benjamin Martinez',
    origin: 'قيد المراجعة',
    status: 'Completed',
    orderId: 'ORD2051',
    txnType: 'Credit',
  },
  {
    txnId: 'TXN10052',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'Lucas Gonzalez',
    origin: 'قيد المراجعة',
    status: 'Pending',
    orderId: 'ORD2052',
    txnType: 'Debit',
  },
  {
    txnId: 'TXN10053',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'Zoe Robinson',
    origin: 'قيد المراجعة',
    status: 'Refunded',
    orderId: 'ORD2053',
    txnType: 'Credit',
  },
  {
    txnId: 'TXN10054',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'Jack Clark',
    origin: 'قيد المراجعة',
    status: 'Completed',
    orderId: 'ORD2054',
    txnType: 'Debit',
  },
  {
    txnId: 'TXN10055',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'Avery Lewis',
    origin: 'قيد المراجعة',
    status: 'Pending',
    orderId: 'ORD2055',
    txnType: 'Credit',
  },
  {
    txnId: 'TXN10056',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'Gabriel Walker',
    origin: 'قيد المراجعة',
    status: 'Completed',
    orderId: 'ORD2056',
    txnType: 'Debit',
  },
  {
    txnId: 'TXN10057',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'Madison Allen',
    origin: 'قيد المراجعة',
    status: 'Refunded',
    orderId: 'ORD2057',
    txnType: 'Credit',
  },
  {
    txnId: 'TXN10058',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'Henry Young',
    origin: 'قيد المراجعة',
    status: 'Pending',
    orderId: 'ORD2058',
    txnType: 'Debit',
  },
  {
    txnId: 'TXN10059',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'Scarlett King',
    origin: 'قيد المراجعة',
    status: 'Completed',
    orderId: 'ORD2059',
    txnType: 'Credit',
  },
  {
    txnId: 'TXN10060',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'Matthew Wright',
    origin: 'قيد المراجعة',
    status: 'Refunded',
    orderId: 'ORD2060',
    txnType: 'Debit',
  },
  {
    txnId: 'TXN10061',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'Carter Moore',
    origin: 'قيد المراجعة',
    status: 'Completed',
    orderId: 'ORD2061',
    txnType: 'Credit',
  },
  {
    txnId: 'TXN10062',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'Grace Taylor',
    origin: 'قيد المراجعة',
    status: 'Pending',
    orderId: 'ORD2062',
    txnType: 'Debit',
  },
  {
    txnId: 'TXN10063',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'Nathan Scott',
    origin: 'قيد المراجعة',
    status: 'Refunded',
    orderId: 'ORD2063',
    txnType: 'Credit',
  },
  {
    txnId: 'TXN10064',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'Riley Harris',
    origin: 'قيد المراجعة',
    status: 'Completed',
    orderId: 'ORD2064',
    txnType: 'Debit',
  },
  {
    txnId: 'TXN10065',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'Dylan Martin',
    origin: 'قيد المراجعة',
    status: 'Pending',
    orderId: 'ORD2065',
    txnType: 'Credit',
  },
  {
    txnId: 'TXN10066',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'Evelyn White',
    origin: 'قيد المراجعة',
    status: 'Completed',
    orderId: 'ORD2066',
    txnType: 'Debit',
  },
  {
    txnId: 'TXN10067',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'Lillian Thompson',
    origin: 'قيد المراجعة',
    status: 'Refunded',
    orderId: 'ORD2067',
    txnType: 'Credit',
  },
  {
    txnId: 'TXN10068',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'Addison Jackson',
    origin: 'قيد المراجعة',
    status: 'Pending',
    orderId: 'ORD2068',
    txnType: 'Debit',
  },
  {
    txnId: 'TXN10069',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'Aiden Lopez',
    origin: 'قيد المراجعة',
    status: 'Completed',
    orderId: 'ORD2069',
    txnType: 'Credit',
  },
  {
    txnId: 'TXN10070',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'Aubrey Lee',
    origin: 'قيد المراجعة',
    status: 'Refunded',
    orderId: 'ORD2070',
    txnType: 'Debit',
  },
  {
    txnId: 'TXN10071',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'Ryan Gonzalez',
    origin: 'قيد المراجعة',
    status: 'Completed',
    orderId: 'ORD2071',
    txnType: 'Credit',
  },
  {
    txnId: 'TXN10072',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'Camila Wilson',
    origin: 'قيد المراجعة',
    status: 'Pending',
    orderId: 'ORD2072',
    txnType: 'Debit',
  },
  {
    txnId: 'TXN10073',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'Lucas Anderson',
    origin: 'قيد المراجعة',
    status: 'Refunded',
    orderId: 'ORD2073',
    txnType: 'Credit',
  },
  {
    txnId: 'TXN10074',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'Mason Roberts',
    origin: 'قيد المراجعة',
    status: 'Completed',
    orderId: 'ORD2074',
    txnType: 'Debit',
  },
  {
    txnId: 'TXN10075',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'Isabelle Clark',
    origin: 'قيد المراجعة',
    status: 'Pending',
    orderId: 'ORD2075',
    txnType: 'Credit',
  },
  {
    txnId: 'TXN10076',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'Theo Lewis',
    origin: 'قيد المراجعة',
    status: 'Completed',
    orderId: 'ORD2076',
    txnType: 'Debit',
  },
  {
    txnId: 'TXN10077',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'Madeline Walker',
    origin: 'قيد المراجعة',
    status: 'Refunded',
    orderId: 'ORD2077',
    txnType: 'Credit',
  },
  {
    txnId: 'TXN10078',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'Chase Young',
    origin: 'قيد المراجعة',
    status: 'Pending',
    orderId: 'ORD2078',
    txnType: 'Debit',
  },
  {
    txnId: 'TXN10079',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'Charlotte King',
    origin: 'قيد المراجعة',
    status: 'Completed',
    orderId: 'ORD2079',
    txnType: 'Credit',
  },
  {
    txnId: 'TXN10080',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'Oliver Wright',
    origin: 'قيد المراجعة',
    status: 'Refunded',
    orderId: 'ORD2080',
    txnType: 'Debit',
  },
  {
    txnId: 'TXN10081',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'Ethan Mitchell',
    origin: 'قيد المراجعة',
    status: 'Completed',
    orderId: 'ORD2081',
    txnType: 'Credit',
  },
  {
    txnId: 'TXN10082',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'Zoe Turner',
    origin: 'قيد المراجعة',
    status: 'Pending',
    orderId: 'ORD2082',
    txnType: 'Debit',
  },
  {
    txnId: 'TXN10083',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'Liam Cooper',
    origin: 'قيد المراجعة',
    status: 'Refunded',
    orderId: 'ORD2083',
    txnType: 'Credit',
  },
  {
    txnId: 'TXN10084',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'Aria Hernandez',
    origin: 'قيد المراجعة',
    status: 'Completed',
    orderId: 'ORD2084',
    txnType: 'Debit',
  },
  {
    txnId: 'TXN10085',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'Miles Davis',
    origin: 'قيد المراجعة',
    status: 'Pending',
    orderId: 'ORD2085',
    txnType: 'Credit',
  },
  {
    txnId: 'TXN10086',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'Sophie Martinez',
    origin: 'قيد المراجعة',
    status: 'Completed',
    orderId: 'ORD2086',
    txnType: 'Debit',
  },
  {
    txnId: 'TXN10087',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'Julian Robinson',
    origin: 'قيد المراجعة',
    status: 'Refunded',
    orderId: 'ORD2087',
    txnType: 'Credit',
  },
  {
    txnId: 'TXN10088',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'Peyton Wilson',
    origin: 'قيد المراجعة',
    status: 'Pending',
    orderId: 'ORD2088',
    txnType: 'Debit',
  },
  {
    txnId: 'TXN10089',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'Sienna Young',
    origin: 'قيد المراجعة',
    status: 'Completed',
    orderId: 'ORD2089',
    txnType: 'Credit',
  },
  {
    txnId: 'TXN10090',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'Blake Richards',
    origin: 'قيد المراجعة',
    status: 'Refunded',
    orderId: 'ORD2090',
    txnType: 'Debit',
  },
  {
    txnId: 'TXN10091',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'Nora Clark',
    origin: 'قيد المراجعة',
    status: 'Completed',
    orderId: 'ORD2091',
    txnType: 'Credit',
  },
  {
    txnId: 'TXN10092',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'Caleb Wright',
    origin: 'قيد المراجعة',
    status: 'Pending',
    orderId: 'ORD2092',
    txnType: 'Debit',
  },
  {
    txnId: 'TXN10093',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'Sadie Johnson',
    origin: 'قيد المراجعة',
    status: 'Refunded',
    orderId: 'ORD2093',
    txnType: 'Credit',
  },
  {
    txnId: 'TXN10094',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'Kai Moore',
    origin: 'قيد المراجعة',
    status: 'Completed',
    orderId: 'ORD2094',
    txnType: 'Debit',
  },
  {
    txnId: 'TXN10095',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'Ruby Lewis',
    origin: 'قيد المراجعة',
    status: 'Pending',
    orderId: 'ORD2095',
    txnType: 'Credit',
  },
  {
    txnId: 'TXN10096',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'Ella Scott',
    origin: 'قيد المراجعة',
    status: 'Completed',
    orderId: 'ORD2096',
    txnType: 'Debit',
  },
  {
    txnId: 'TXN10097',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'Ivy Sanchez',
    origin: 'قيد المراجعة',
    status: 'Refunded',
    orderId: 'ORD2097',
    txnType: 'Credit',
  },
  {
    txnId: 'TXN10098',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'Landon King',
    origin: 'قيد المراجعة',
    status: 'Pending',
    orderId: 'ORD2098',
    txnType: 'Debit',
  },
  {
    txnId: 'TXN10099',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'Mila Baker',
    origin: 'قيد المراجعة',
    status: 'Completed',
    orderId: 'ORD2099',
    txnType: 'Credit',
  },
  {
    txnId: 'TXN10100',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'Hudson Green',
    origin: 'قيد المراجعة',
    status: 'Refunded',
    orderId: 'ORD2100',
    txnType: 'Debit',
  },
  {
    txnId: 'TXN10101',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'Victoria Garcia',
    origin: 'قيد المراجعة',
    status: 'Completed',
    orderId: 'ORD2101',
    txnType: 'Credit',
  },
  {
    txnId: 'TXN10102',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'Brooklyn Hall',
    origin: 'قيد المراجعة',
    status: 'Pending',
    orderId: 'ORD2102',
    txnType: 'Debit',
  },
  {
    txnId: 'TXN10103',
    dateCreated: '2024-04-06',
    amount: 'SAR 18,750.00',
    userName: 'Xavier Nelson',
    origin: 'قيد المراجعة',
    status: 'Refunded',
    orderId: 'ORD2103',
    txnType: 'Credit',
  },





  
  // Continue adding more entries up to 20 as needed
];function randomDate(start:any, end:any) {
  return new Date(start.getTime() + Math.random() * (end.getTime() - start.getTime())).toISOString().split('T')[0];
}

transactionsData.forEach(transaction => {
  transaction.dateCreated = randomDate(new Date(2024, 1, 31), new Date(2024, 1, 1));
});

for (let i = 0; i < 30; i++) {
  transactionsData.unshift({
    txnId: `TXN${10031 + i}`,
    dateCreated: '2024-04-08',
    amount: 'SAR 18,750.00',
    userName: `User ${i + 1}`,
    origin: 'قيد المراجعة',
    status: 'Pending',
    orderId: `ORD20${31 + i}`,
    txnType: i % 2 === 0 ? 'Credit' : 'Debit',
  });
}
const TableOne = () => {
  return (
    <div className="rounded-sm border border-stroke bg-white px-5 pt-6 pb-2.5 shadow-default dark:border-strokedark dark:bg-boxdark sm:px-7.5 xl:pb-1">
      <h4 className="mb-6 text-xl font-semibold text-black dark:text-white">
      التحويلات الاخيرة

      </h4>
      <div className="overflow-x-auto">
        <div className="align-middle inline-block min-w-full">
          <div className="shadow overflow-hidden border-b border-stroke sm:rounded-sm">
            <table className="min-w-full divide-y divide-stroke">
              <thead>
                <tr>
                  <th className="text-center align-middle px-6 py-3 text-left text-xs font-medium text-black dark:text-white uppercase tracking-wider">
                    Txn ID
                  </th>
                  <th className=" text-center align-middle px-6 py-3 text-left text-xs font-medium text-black dark:text-white uppercase tracking-wider">
                  تاريخ الإنشاء

                  </th>
                  <th className="text-center align-middle px-6 py-3 text-left text-xs font-medium text-black dark:text-white uppercase tracking-wider">
                  كمية

                  </th>
                  <th className="text-center align-middle px-6 py-3 text-left text-xs font-medium text-black dark:text-white uppercase tracking-wider">
                     اسم المستخدم
                  </th>
                
                  <th className="text-center align-middle px-6 py-3 text-left text-xs font-medium text-black dark:text-white uppercase tracking-wider">
                    الحالة
                  </th>
                 
                </tr>
              </thead>
              <tbody className="bg-white divide-y divide-stroke dark:divide-strokedark dark:bg-boxdark">
                 {transactionsData.map((transaction, idx) => (
                  <tr key={idx}>
                    <td className="text-center align-middle px-6 py-4 whitespace-nowrap text-sm text-black dark:text-white">
                      {transaction.txnId}
                    </td>
                    <td className="text-center align-middle px-6 py-4 whitespace-nowrap text-sm text-black dark:text-white">
                      {transaction.dateCreated}
                    </td>
                    <td className="text-center align-middle px-6 py-4 whitespace-nowrap text-sm text-black dark:text-white">
                      {transaction.amount}
                    </td>
                    <td className="text-center align-middle px-6 py-4 whitespace-nowrap text-sm text-black dark:text-white">
                      {transaction.userName}
                    </td>
                    <td className="text-center align-middle px-6 py-4 whitespace-nowrap text-sm text-black dark:text-white">
                      {transaction.status}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  );
};

export default TableOne;
